POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "bob",
    "email": "bob@gmail.com",
    "password": "123456789"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "123456789"
}

###

GET http://localhost:5000/api/auth/refresh_token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmJiMjE0NTI0NTU0NWVhNzBiN2I3NjgiLCJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHl2WTYyWFk2cjg4U3JIUDBKVlpqRXVHNTRScDJsdXNoRTQuZVVxOXVDMGNyd0k2dXlqdW0uIiwiY3JlYXRlZEF0IjoiMjAyMi0wNi0yOFQxNTo0MTozNC4zNDBaIiwiX192IjowLCJpYXQiOjE2NTY0MzQ3Njh9.SpTtpEIf6nzJv1f4ilIiUd1c_FU4pqjJ3SyGkY815-k"
}

###

GET http://localhost:5000/api/users/get/62bb2145245545ea70b7b768
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjItMDYtMjhUMTU6NDE6MzQuMzQwWiIsImlhdCI6MTY1NjQzNDgyNiwiZXhwIjoxNjU2NDM1NDI2fQ.x17Ah7KPytUkreAOYVj5xTdtkmlVYpcwJFcH0i2hxC0
