POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "bob",
    "email": "bob@gmail.com",
    "password": "123456789"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "123456789"
}

###

GET http://localhost:5000/api/auth/refresh_token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmJiZTVkODRmZmE4NGRiMGQxZjA5YjUiLCJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDhxSDZNQWVqWmN5MVlTQ29yRTZYOU9KR09ZUzFSaW9kS1doWDViZENpQS9xZ3B6VUpkVndpIiwiY3JlYXRlZEF0IjoiMjAyMi0wNi0yOVQwNTozOTo1My43MDFaIiwiX192IjowLCJpYXQiOjE2NTY1MDQxNjN9.FrVkYGe8LwNGeZM8Lw3zGnG_xoXpQ8NA8fPcO-c3xLw"
}

###

PUT http://localhost:5000/api/carts/add/62bc401349d897d205a2d530
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmJiZTVkODRmZmE4NGRiMGQxZjA5YjUiLCJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjItMDYtMjlUMDU6Mzk6NTMuNzAxWiIsImlhdCI6MTY1NjUwNDc4NSwiZXhwIjoxNjU2NTA1Mzg1fQ.rQNoTqsB0Db2Xjb33dnhjeYokgIsVvZLTcreoy-fcQs

{
    "item": "62bc39c6972482f3074248af"
}
