POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "bob",
    "email": "bob@gmail.com",
    "password": "123456789"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "bob@gmail.com",
    "password": "123456789"
}

###

GET http://localhost:5000/api/auth/refresh_token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmJiMjE0NTI0NTU0NWVhNzBiN2I3NjgiLCJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJHl2WTYyWFk2cjg4U3JIUDBKVlpqRXVHNTRScDJsdXNoRTQuZVVxOXVDMGNyd0k2dXlqdW0uIiwiY3JlYXRlZEF0IjoiMjAyMi0wNi0yOFQxNTo0MTozNC4zNDBaIiwiX192IjowLCJpYXQiOjE2NTY0ODAwMzN9._dBlr0NpzTbN0a2PMjlwJL6nHm8LxQlmWewvOP6AYi8"
}

###

PUT http://localhost:5000/api/users/edit/62bb2145245545ea70b7b768
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmJiMjE0NTI0NTU0NWVhNzBiN2I3NjgiLCJ1c2VybmFtZSI6ImJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjItMDYtMjhUMTU6NDE6MzQuMzQwWiIsImlhdCI6MTY1NjQ4MDIyNCwiZXhwIjoxNjU2NDgwODI0fQ.3scAP5j-oKUba_Tt_qUg6sBUFqtzhA_jf5BH2_zzUoE

{
    "username": "bob",
    "email": "bob@gmail.com"
}
